export const events = [
  {
    id: '64d2f1d5c5b62a3a9f4e8f4e',
    title: 'AI Innovation Summit 2024',
    imageUrl: '/events/ai-summit.jpeg',
    startDate: 'August 15, 2024',
    startTime: '9:00 AM',
    endDate: 'August 15, 2024',
    endTime: '5:00 PM',
    location: 'San Francisco Tech Hub, San Francisco',
    creatorName: 'Emily Clarke',
    description:
      'Explore the future of artificial intelligence with industry leaders. Attend workshops, panels, and networking sessions.',
    category: 'Technology',
    attendeesCount: 200,
    price: 299.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f4f',
    title: 'Green Energy Expo 2024',
    imageUrl: '/events/green-energy-expo.jpeg',
    startDate: 'August 18, 2024',
    startTime: '10:00 AM',
    endDate: 'August 18, 2024',
    endTime: '6:00 PM',
    location: 'Denver Convention Center, Denver',
    creatorName: 'Michael Smith',
    description:
      'Discover the latest innovations in renewable energy. Engage with experts and learn about sustainable practices.',
    category: 'Environment',
    attendeesCount: 120,
    price: 249.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f50',
    title: 'Digital Marketing Conference 2024',
    imageUrl: '/events/digital-marketing.jpeg',
    startDate: 'August 20, 2024',
    startTime: '8:00 AM',
    endDate: 'August 20, 2024',
    endTime: '4:00 PM',
    location: 'New York Hilton, New York',
    creatorName: 'Sarah Johnson',
    description:
      'Gain insights into the newest trends in digital marketing. Participate in sessions led by top marketing professionals.',
    category: 'Marketing',
    attendeesCount: 250,
    price: 349.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f51',
    title: 'Health Tech Summit 2024',
    imageUrl: '/events/health-tech-summit.jpeg',
    startDate: 'August 22, 2024',
    startTime: '9:00 AM',
    endDate: 'August 22, 2024',
    endTime: '5:00 PM',
    location: 'Los Angeles Convention Center, Los Angeles',
    creatorName: 'David Lee',
    description:
      'Join healthcare innovators to explore the intersection of technology and medicine. Network and discover new health tech solutions.',
    category: 'Healthcare',
    attendeesCount: 180,
    price: 279.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f52',
    title: 'Blockchain & Crypto Forum 2024',
    imageUrl: '/events/blockchain-crypto.jpeg',
    startDate: 'August 25, 2024',
    startTime: '10:00 AM',
    endDate: 'August 25, 2024',
    endTime: '6:00 PM',
    location: 'Miami Beach Convention Center, Miami',
    creatorName: 'Laura Wilson',
    description:
      'Dive into the world of blockchain and cryptocurrency. Learn from experts and discuss the future of digital finance.',
    category: 'Finance',
    attendeesCount: 220,
    price: 399.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f53',
    title: 'Robotics Showcase 2024',
    imageUrl: '/events/robotics-showcase.jpeg',
    startDate: 'August 28, 2024',
    startTime: '11:00 AM',
    endDate: 'August 28, 2024',
    endTime: '7:00 PM',
    location: 'Seattle Science Center, Seattle',
    creatorName: 'James Brown',
    description:
      'Experience cutting-edge robotics technology. Interact with robots and attend demonstrations by leading engineers.',
    category: 'Technology',
    attendeesCount: 140,
    price: 299.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f54',
    title: 'Cybersecurity Summit 2024',
    imageUrl: '/events/cybersecurity-summit.jpeg',
    startDate: 'August 30, 2024',
    startTime: '9:00 AM',
    endDate: 'August 30, 2024',
    endTime: '5:00 PM',
    location: 'Chicago Conference Center, Chicago',
    creatorName: 'Anna Martinez',
    description:
      'Understand the latest threats and defenses in cybersecurity. Hear from top experts and participate in interactive sessions.',
    category: 'Security',
    attendeesCount: 200,
    price: 349.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f55',
    title: 'Virtual Reality Expo 2024',
    imageUrl: '/events/vr-expo.jpeg',
    startDate: 'August 31, 2024',
    startTime: '10:00 AM',
    endDate: 'August 31, 2024',
    endTime: '6:00 PM',
    location: 'Austin Convention Center, Austin',
    creatorName: 'Robert Taylor',
    description:
      'Immerse yourself in the world of virtual reality. Discover new VR applications and engage with leading VR developers.',
    category: 'Technology',
    attendeesCount: 160,
    price: 279.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f56',
    title: 'Startup Showcase 2024',
    imageUrl: '/events/startup-showcase.jpeg',
    startDate: 'September 2, 2024',
    startTime: '9:00 AM',
    endDate: 'September 2, 2024',
    endTime: '4:00 PM',
    location: 'Boston Innovation Hub, Boston',
    creatorName: 'Olivia Davis',
    description:
      'Meet the latest startups and learn about their groundbreaking ideas. Network with entrepreneurs and investors.',
    category: 'Business',
    attendeesCount: 130,
    price: 199.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f57',
    title: 'Tech & Innovation Forum 2024',
    imageUrl: '/events/tech-innovation.jpeg',
    startDate: 'September 5, 2024',
    startTime: '10:00 AM',
    endDate: 'September 5, 2024',
    endTime: '5:00 PM',
    location: 'Toronto Conference Center, Toronto',
    creatorName: 'William Clark',
    description:
      'Explore emerging technologies and innovative solutions. Attend keynotes and panels with industry thought leaders.',
    category: 'Technology',
    attendeesCount: 190,
    price: 329.99,
  },
  {
    id: '64d2f1d5c5b62a3a9f4e8f58',
    title: 'Future of Work Summit 2024',
    imageUrl: '/events/future-of-work.jpeg',
    startDate: 'September 7, 2024',
    startTime: '8:00 AM',
    endDate: 'September 7, 2024',
    endTime: '4:00 PM',
    location: 'Vancouver Convention Center, Vancouver',
    creatorName: 'Sophia Lee',
    description:
      'Discuss the evolving landscape of work and workforce technology. Engage with experts and explore new work trends.',
    category: 'Business',
    attendeesCount: 170,
    price: 259.99,
  },
];
